### PR TITLE
Jack updates v2

### LINKED ISSUE #232: Multiple footnotes created when adding p values to footnotes using *
When you add a description of p-values/significance levels to a theme61 footnote (e.g. * p < 0.10, ** p < 0.05 ...) they are broken up into separate footnotes.

### PR DESCRIPTION
**Pull request by JackBuckley**
## Issues and features

Closes #232, #229, #227 and #222.

## Improved functionality

* The `chart_type` argument in `save_e61` has been updated so that it now allows you to adjust the aspect ratio of your chart in an easy and consistent way. There are three valid values `Normal` (aspect ratio of 0.75), `Wide` (aspect ratio of 0.5) and `Square` (aspect ratio of 1). You can also supply a list of values to `save_e61` if you are saving multiple charts.
* Added the ability to save JPEGs. This functions in a similar way to how PNGs are currently saved - you can use the `res` argument in `save_e61` to adjust the resolution.

## Bug fixes

* Fixed an issue where y-axis labels were not being aligned correctly when saving multiple plots at the same time. 
* Fixed an issue where where you could not use a * in footnotes (e.g. for describing the level of statistical significance) without `save_e61` interpreting this as a new footnote.

### CODE REVIEW

File: R/save-helpers.R [hunk 1]
```diff
@@ -80,25 +84,25 @@ get_plot_width <- function(chart_type){
...
-
-  } else {
-    plot_base_size <- plot_base_size * 20 / get_plot_width("MN")
-  }
-
-  return(plot_base_size)
-}
+#' #' Get the base size of the plot
+#' #' @noRd
+#' get_base_size <- function(chart_type, plot_base_size = 10){
```
Comment (aaronw22) [inline R/save-helpers.R:89]: Is this meant to be turned into roxygen comments?

File: R/save_e61.R [hunk 2]
```diff
@@ -69,8 +70,8 @@
 save_e61 <- function(filename,
                      ...,
                      plot = last_plot(),
-                     format = c("svg", "pdf", "eps", "png"),
-                     chart_type = c("MN", "RN", "PPT"),
+                     format = c("svg", "pdf", "eps", "png", "jpg"),
+                     chart_type = NULL,
```
Comment (aaronw22) [inline R/save_e61.R:74]: We should enforce the `chart_type` argument to be one of the 3 options. Also would strongly prefer lowercase arguments -- `c("normal", "wide", "square")`.

File: R/save_e61.R [hunk 3]
```diff
@@ -17,9 +17,10 @@
 #' @param plot (single-panel specific) Name of the plot object to save. Defaults
 #'   to the last plot displayed so usually you do not need to provide this
 #'   argument explicitly.
-#' @param chart_type String. Type of chart. This is used to set sensible chart
-#'   widths based on the width of text in each document. Options are "MN" (for
-#'   micronotes), "RN" (research notes) or "PPT" (PowerPoints).
+#' @param chart_type String, or vector of strings if saving multiple plots.
+#'   Type of chart. This is used to set sensible chart widths based on the type
+#'   of plot you are saving. Options are "Normal" (default; for normal charts),
+#    "Wide" (for time series notes) or "Square" (for scatter plots).
```
Comment (aaronw22) [inline R/save_e61.R:23]: time series graphs?

File: R/aes_labs.R [hunk 4]
```diff
@@ -527,7 +566,7 @@ update_plot_label <- function(plot, chart_type, base_size){
       if(!is.null(attr(label, "adj_plot_label"))){
 
         # 4 - get the base size of a micronote
-        mn_base_size <- get_base_size(chart_type = "MN")
+        mn_base_size <- 10
```
Comment (aaronw22) [inline R/aes_labs.R:569]: Is the reference to a micronote a relic from the prev functionality? Would be good to remove to avoid future confusion

**Review by aaronw22 — APPROVED** [review]

File: R/save_e61.R (hunk 3 above)
Comment (aaronw22) [inline R/save_e61.R]: *time series graphs?

**Review by aaronw22 — APPROVED** [review]

File: R/aes_labs.R (hunk 4 above)
Comment (JackBuckley) [reply R/aes_labs.R:569]: I think I deleted the chart_type == "MN"? Or am I reading that wrong?

File: R/save_e61.R (hunk 3 above)
Comment (JackBuckley) [reply R/save_e61.R]: Pretty sure that is fixed in the latest version, do I need to refresh?

File: R/aes_labs.R (hunk 4 above)
Comment (aaronw22) [reply R/aes_labs.R:569]: Mostly about the code comment + object naming being confusing in the future

File: R/save_e61.R (hunk 3 above)
Comment (aaronw22) [reply R/save_e61.R]: The diff still shows as time series notes for me on github, but not 100% sure

Comment (aaronw22) [reply R/save_e61.R]: Nope, you're good. The Files changed tab didn't include the latest commit for some reason.

File: R/aes_labs.R (hunk 4 above)
Comment (JackBuckley) [reply R/aes_labs.R:569]: Yeah fair point, I'll update
