### PR TITLE
Plot labels now respect facet ordering and other facet label bug fixes 

### LINKED ISSUE #217: Facet ordering reset by `plot_label()`
**Describe the bug**
Ordered factor is ignored when the facets are arranged when `plot_label()` is used to add plot labels.

**Code to reproduce**

```
library(ggplot2)
library(theme61)

df <- data.frame(grp = 1:3, val = rep(1, 3))
df$grp <- ordered(df$grp, 3:1)

# this works
ggplot(df, aes(x = val, y = val)) +
  geom_point() +
  facet_wrap(~grp)

# this resets the order
ggplot(df, aes(x = val, y = val)) +
  geom_point() +
  facet_wrap(~grp) +
  plot_label("a point", 1.25, 1, facet_name = "grp", facet_value = "1") +
  scale_x_continuous_e61(c(1, 2))
```

**Expected behavior**
Facet order follows the ordered factor that is the input vector.

### LINKED ISSUE #220: Plot label on facets now does not work by default and throws unclear error mesage
**Describe the bug**
Error thrown when adding a plot label to a faceted chart is unclear.

**Code to reproduce**
Add a plot label call to a faceted chart without specifying the facet variable name or level

**Expected behavior**
The code should either throw a clear error with a description of how to properly apply plot label to a faceted chart or as before just apply the labels to both (my preference is for the first)

**Screenshots**
theme61 facet bug

### PR DESCRIPTION
**Pull request by aaronw22**
## Describe your changes

Fix and closes #217 #220

### For feature branches

- [x] I have written tests covering functions I have added or changed.
- [x] I have run tests and they all pass.
- [x] I have ensured all new functions show up in the `_pkgdown.yml` file.
- [x] I have updated the package documentation with `devtools::document()`.
- [x] I have updated `DESCRIPTION` with any new package dependencies.

### CODE REVIEW

File: R/plot_label.R [hunk 1]
```diff
@@ -33,20 +32,28 @@ plot_label <-
            geom = c("text", "label"),
            angle = 0,
            facet_name = NULL,
```
Comment (Anile61) [inline R/plot_label.R]: why has facet_name not also been removed alongside facet_value? And why has facet_variable been introduced given the intention of passing the facet variable(s) directly?

File: R/plot_label.R [hunk 2]
```diff
@@ -33,20 +32,28 @@ plot_label <-
...
+    # Hard deprecate old args if used
+    if (!is.null(facet_name) || !is.null(facet_value)) {
+      lifecycle::deprecate_stop(
+        when = "0.7.1",
+        what = "theme61::plot_label(facet_name = '', facet_value = '')",
+        with = "theme61::plot_label(<facet_var> = <facet_value>)",
+        details = paste0(
+          "Facet targeting is now done by passing the facet variable(s) directly.\n",
+          "Example:\n",
+          "  plot_label('a point', 1.25, 1, grp = '1')"
```
Comment (Anile61) [inline R/plot_label.R]: Could be more explicit in the example in the error message that 'grp' is the facet variable name. Took me a while to figure that out.

File: R/plot_label.R [hunk 3]
```diff
@@ -56,69 +63,234 @@ plot_label <-
...
+        stop("`", nm, "` must be length 1 or the number of labels (", n, ").")
+      }
+      plot_lab_data[[nm]] <- v
+    }
+  }
+
+  facet_vars <- .get_facet_vars(plot)
+
+  if (length(facet_vars)) {
+    have <- intersect(facet_vars, names(plot_lab_data))
```
Comment (Anile61) [inline R/plot_label.R]: would it be useful to check against names in extra instead of names in plot_lab_data in case they named their facet variable(s) after one of the other vars?

File: R/plot_label.R (hunk 1 above)
Comment (aaronw22) [reply R/plot_label.R]: Ahh that's a typo. `facet_value` should still be there not w/e `facet_variable` is. They remain as deprecated arguments until after the next major release so users get a helpful error message when they invoke them instead of the new syntax. See your next comment on the deprecation example.

File: R/plot_label.R (hunk 2 above)
Comment (aaronw22) [reply R/plot_label.R]: Updated!

File: R/plot_label.R (hunk 3 above)
Comment (aaronw22) [reply R/plot_label.R]: Good spot, I've refactored to deal with the broader issue of reserved column name matches

**Comment by aaronw22** [comment]
Hi @Anile61. Thanks for your review, it was very detailed and helpful! I've made a number of changes to the code that fix a few things I overlooked previously as well as the things you mentioned.

**Review by Anile61 — APPROVED** [review]
